### ISSUE TITLE
Idea: Use ORES scoring for article completeness

### ISSUE THREAD

**Issue by JeanFred** [wikimedia-france/macommune#2]
Seen that on [the outreach dashboard](https://outreachdashboard.wmflabs.org):

> The 'Structural Completeness' score represents how closely an article fits
>       the mold of a mature Wikipedia article, based on the machine learning-based
>       Objective Revision Evaluation Service (https://ores.wikimedia.org/). These
>       scores are calculated based on the size of an article, the number of
>       references and wikilinks, and other basic text features. A high score
>       usually indicates that an article follow Wikipedia's conventions for the
>       structure of a good article, but it does not take into account the content
>       itself. (These scores are only available for English Wikipedia articles.)

Could be a nice additional scoring source.

**Comment by Ash-Crow** [comment]
That sounds nice! But we currently only rate the French Wikipedia and per your quote, that scoring in only available on the English one.

**Comment by JeanFred** [comment]
That documentation snippet is probably outdated − ORES does have the `wp10` scoring method for frwiki \o/
https://meta.wikimedia.org/wiki/Objective_Revision_Evaluation_Service/wp10#French_Wikipedia_.28frwiki.29
