### ISSUE TITLE
500 error when searching a commune

### ISSUE THREAD

**Issue by JeanFred** [wikimedia-france/macommune#3]
The instance at `macommune.wikipedia.fr` throws a 500 exception when using the search function

See eg:
https://macommune.wikipedia.fr/commune/search?title=Clayes

Returns
```
Oops! An Error Occurred

The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
```

**Comment by Ash-Crow** [comment]
The site is not in production yet and is currently under heavy developpement by @0x010C, so downtimes are to be expected at times.
