### ISSUE TITLE
Link to Wikidata on commune page is broken

### ISSUE THREAD

**Issue by JeanFred** [wikimedia-france/macommune#9]
Steps to reproduce:
* https://macommune.wikipedia.fr/Q527676/Fondettes
* The Link behind “Wikidata” is `https://www.wikidata.org/wiki/undefined`

**Comment by JeanFred** [comment]
Thanks @Ash-Crow ! That was fast :)

**Comment by Ash-Crow** [comment]
I so much wish that every bug were that easy to fix ^^'
